### PR TITLE
Allow multiple protos with the same basename

### PR DESCRIPTION
**Pull request by tamird**
continuation of #24 and #30.

Probably needs a test

### CODE REVIEW

**Comment by alexeyxo** [comment]
I do not see the sense in this pull request. I have already all corrected and added.

**Comment by alexeyxo** [comment]
In your version of compiler, not correct class names. 
```swift
internal struct GoogleProtobufUnittestCustomOptionsRoot {
   internal static var sharedInstance : GoogleProtobufUnittestCustomOptionsRoot {
   }
}
```

**Comment by tamird** [comment]
In my experience, swift will refuse to compile two files with the same basename in the same compilation. e.g. `foo/bar.swift` and `baz/bar.swift` will fail to compile - this PR addresses that issue.

**Comment by tamird** [comment]
Is this actually resolved? I believe it is not.

**Pull request closed without merging**
