### PR TITLE
[WIP] protobuf 2.6 - new swift 3 preview 1

### PR DESCRIPTION
**Pull request by goloveychuk**

### CODE REVIEW

**Comment by goloveychuk** [comment]
@alexeyxo 
need your help
https://github.com/alexeyxo/protobuf-swift/pull/146/commits/94f078f2da45dfc1ebd12774d2c4644be83d0c03#diff-cd7c3d91bc2f54f45f2ee1623b01bd2f

look at  Source/Google.Protobuf.Descriptor.proto.swift
Before this commit it was migrated by migration tool
After - generated by c++ plugin.
The important change is 
```swift
public private(set) var extensionRange:Array<ExtensionRange>  = Array<Google.Protobuf.DescriptorProto.ExtensionRange>()
//to
public private(set) var extensionRange:Array<Google.Protobuf.DescriptorProto.ExtensionRange>  = Array<Google.Protobuf.DescriptorProto.ExtensionRange>()
```
`Google.Protobuf.DescriptorProto.ExtensionRange` should be `ExtensionRange`
Otherway swift tell that it's circular import 
This is generated by $classname$ but I can't change it to make works.

**Comment by kouky** [comment]
@goloveychuk I'm having the same issue with this branch under Xcode 8 beta with Swift Preview 1. Is there a workaround for the time being?

I'm trying to get it to compile with Carthage, I changed the `extensionRange` type to `Array<ExtensionRange>` as per your comment. However there was a subsequent error at line `8325` in `Google.Protobuf.Descriptor.proto.swift` - `error: could not infer type for 'location'` which corresponds with this line in the source

```
    public private(set) var location:Array<Google.Protobuf.SourceCodeInfo.Location>  = Array<Google.Protobuf.SourceCodeInfo.Location>()
```

Not sure how to fix these.

**Comment by goloveychuk** [comment]
@kouky 
you can checkout first commit from PR, I changed descriptor file manually, it's compiling. You can copy that.

**Comment by alexeyxo** [comment]
I currently work above this problems(circular import). I saw fix in apple-swift repository. It didn't go to the Preview 2.

**Comment by alexeyxo** [comment]
Currently Bug is fixed in DP3.

**Comment by goloveychuk** [comment]
didn't know this is bug. so this pr is incorrect and could be closed

**Pull request closed without merging**
