### PR TITLE
Fix type cast to AnyObject for Swift 3 Beta 6 and other quick issues

### PR DESCRIPTION
**Pull request by felixLam**
This only resolves the "low hanging" fruits. The tougher issues around `UnsafeMutablePointer` persist, but this might get some of the leg work out of the way for you.

### CODE REVIEW

**Comment by gegles** [comment]
Thank you so much, I had started to resolve some of these issues as well.

For the AnyObject, instead of casting everything explicitly (as AnyObject), I tweaked the compiler plugin to generate Dictionary with "Any" everywhere...... that part seem to compile.

I am not enough of a Swift and Protobuf expert to determine whether that's the better path forward or not.... Just wanted to let you know in case it had not been considered.

I will checkout your PR and give it a go....

Thanks. G.

**Comment by felixLam** [comment]
@gegles I haven't really looked into the compiler plugin to be honest. The only issue that I wasn't able to brute-force has been "worked around" in https://github.com/iosphere/protobuf-swift/tree/ProtoBuf3.0-Swift3.0-quickfix

**Comment by gegles** [comment]
@felixLam I tried quickly, I think the open vs. public thing will need to be addressed better as obviously my generated code extends protobuf-swift's classes (GeneratedMessage, etc..) and one cannot override "public" classes/methods anymore from another package only "open" classes/methods. I also think that a lot of these things (AnyObject and public/open) are better addressed at the compiler level .....

**Comment by felixLam** [comment]
@gegles The Compiler absolutely needs to be adjusted too as this currently generates code that also does not work on Swift 3. The open/public debate is a whole other issue. I am also not too happy with the work around in this PR, but it allowed me to continue working on the project.

**Pull request merged**
