### PR TITLE
Preserve file paths

### PR DESCRIPTION
**Pull request by tamird**
@alexeyxo probably best to review this commit-by-commit. The last commit is a cleanup that removes a ton of duplicated files (so the diff is enormous).

### CODE REVIEW

**Comment by tamird** [comment]
link to the commits with whitespace removed:
https://github.com/tamird/protobuf-swift/commit/18aed768d69c3c7f9b64069be9dda684a3f5554e?w=1
https://github.com/tamird/protobuf-swift/commit/9fa0c06f53a272e6b70ace7a95fb58401552d825?w=1
https://github.com/tamird/protobuf-swift/commit/66584eb714112d4630458e0576ea942c46a347db?w=1

**Comment by alexeyxo** [comment]
I can not take this pull reguest.
Not correctly named class "package_name + class name".
Shall be as follows:

```protobuf
package = "google.protobuf"
message TestA {

}
```

```swift
internal struct Google
{
     internal struct Protobuf
     {
          internal class TestA {}
     }
}
```

In other proto files:

```swift
extension Google.Protobuf
{
      internal class TestB {}
}
```

**Comment by alexeyxo** [comment]
Make a separate pull request with corrections for # 24

**Comment by alexeyxo** [comment]
https://github.com/tamird/protobuf-swift/commit/18aed768d69c3c7f9b64069be9dda684a3f5554e
I agree with this fix.

**Comment by tamird** [comment]
@alexeyxo yes, the behaviour in this PR is not correct, but neither is the behaviour prior to this PR (no wrapping `internal struct`s are ever generated. Perhaps you can help make the other necessary changes?

**Comment by alexeyxo** [comment]
I started doing.
https://github.com/alexeyxo/protobuf-swift/commit/758289504a3bb0c1a21831771f6688f8b06842ba https://github.com/alexeyxo/protobuf-swift/commit/ccd779e2ac501d2f7dd3d49bec42aeffe0dcd23e https://github.com/alexeyxo/protobuf-swift/commit/414bc5ce7587edaf522fda010a3820480715ad35
I will do it at weekend.

**Comment by tamird** [comment]
after rebasing this on top of #30 i can get things to compile!

**Comment by tamird** [comment]
@alexeyxo turns out my filename fix isn't sufficient because the swift compiler does this:
```
...
<unknown>:0: error: filename "Verify.pb.swift" used twice: '/foo/Verify.pb.swift' and '/bar/Verify.pb.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Pull request closed without merging**
